[goldmark]
  [goldmark.renderer]
    unsafe = true
  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true
      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

[tableOfContents]
  startLevel = 2
  endLevel = 3
  ordered = false

[highlight]
  noClasses = false
