[[main]]
  name = "About"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "Journal"
  pageRef = "journal"
  weight = 30

[[main]]
  name = "Gallery"
  pageRef = "gallery"
  weight = 40

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 50
